### ISSUE TITLE
GIMP

### ISSUE THREAD

**Issue by jedahan** [kiss-community/repo-community#31]
Had to use beta channel of flatpak to run on wayland

    kiss build repo-flatpak
    kiss install repo-flatpak
    source /etc/profile
    
    kiss build flatpak
    kiss install flatpak

    flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo # beta needed for native wayland support
    flatpak install org.gimp.GIMP
    flatpak make-current --user org.gimp.GIMP beta

    flatpak run --user org.gimp.GIMP

**Comment by mmatongo** [comment]
credits to @eudaldgr 

https://github.com/eudaldgr/kiss-garbage/tree/1ac916eee7f0a21e3bc4b29246a1ec53f5a1bf04/gfx/gimp

**Comment by eudaldgr** [comment]
This not build anymore, needs `gtk+2`. I'm working on build the 2.99.4 version with `gtk+3` only.

**Comment by mmatongo** [comment]
That's unfortunate, at least we have a POC that has worked and can build on it.

**Comment by eudaldgr** [comment]
[`gimp 2.99.4`](https://github.com/eudaldgr/kiss-garbage/tree/master/gfx/gimp)

In order to build, it need to add some [hooks](https://github.com/eudaldgr/kiss-garbage/blob/master/gfx/README.md), and rebuild packages like `gtk+3`, `pango`...

![current](https://user-images.githubusercontent.com/50481714/104102667-3b695000-529e-11eb-80c9-0c64cc434746.png)

**Comment by dilyn-corner** [comment]
Closing this as it's resolved
