### ISSUE TITLE
webkit: not capable of solving reCAPTCHA

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#331]
Hello @git-bruh there is still a problem, the browser can't solve the reCAPTCHA. 
I use this for testing https://patrickhlauke.github.io/recaptcha/
The initial I am not robot box load now, (with the previous version it would never load at all) 
but when I click that square nothing happens and after a while I see this:
![2021-04-24-111932_1010x611_scrot](https://user-images.githubusercontent.com/33268383/115963827-a28ad780-a510-11eb-92b5-0cc3c4bdf2be.png)

This is a bug because on arch linux it works perfectly. 
I suspect this may be because of some build options not enabled?

**Comment by git-bruh** [comment]
On my glibc chroot I'm able to load the captcha 
![2021-04-25-093826_956x538_scrot](https://user-images.githubusercontent.com/67585967/115980444-4c537e00-a57c-11eb-9725-8ed694a9ca3d.png) but on musl it doesn't work... Both are built with same config, I'll experiment with a few options still. Could you try installing a webkit browser in a void chroot and see if it works there since we're using the same patch ?

**Comment by kyx0r** [comment]
I have a working void-musl install and it seems like I am up to date with the repos. However, the reCAPCHA does not even load. 
![2021-04-25-083328_737x388_scrot](https://user-images.githubusercontent.com/33268383/115995529-26a19580-a5cb-11eb-8c5b-c4bd76bd80c4.png)
![2021-04-25-083438_1290x154_scrot](https://user-images.githubusercontent.com/33268383/115995531-26a19580-a5cb-11eb-844a-ffc2747b7603.png)

**Comment by kyx0r** [comment]
There are interesting points, the paypal.com works, but duckduckgo doesn't maybe they haven't updated their repos yet?? Or that fix is not in ? I may need to actually build it from source so be sure.

**Comment by kyx0r** [comment]
Damn it... I can't build void packages because my kernel does not support xbps-uunshare, hold this will take a bit longer to setup

**Comment by kyx0r** [comment]
@git-bruh Well I failed to setup a test void chroot build enviroment, and maintainer over there does not care about us, nor the packages so I be debugging this by myself for now. However I did pull their latest webkit_2 binary version that the same bug is present there too, so I guess no point in void build at all.

**Comment by git-bruh** [comment]
I see some instructions [here](https://trac.webkit.org/wiki/WebKitGTK/Debugging) to debug, but I'm not sure if anything related to the issue we're having here would show up in logs since it's not a crash, also logging support is enabled by the `-DUSE_SYSTEMD=ON` option so i guess some systemd libraries are require to build it :confused:

**Comment by q66** [comment]
https://github.com/void-linux/void-packages/commit/b0b0bbe0ad217f9239282898ae65e7767d4704d9

**Comment by dilyn-corner** [comment]
Void might not care about us, but they sure are helpful.
