### ISSUE TITLE
qemu: build is broken

### ISSUE THREAD

**Issue by illiliti** [kiss-community/repo-community#367]
log:
https://termbin.com/1s5r

fix:
Replace patches/002-syscall.patch with https://git.alpinelinux.org/aports/tree/community/qemu/fix-sigevent-and-sigval_t.patch (not sure if this is proper fix though)

also:
https://github.com/kiss-community/repo-community/blob/1d1a462bdacccf087cbd9c306f21e3324abc8cd9/community/qemu/build#L8
This sed call doesn't trim bash-specific `-o pipefail`.

also 2:
Looks like ./configure is useless because qemu uses meson underhood either way. Should we swap to meson or at least add `meson make` to depends?

also 3:
We shouldn't build tests. They are only waste of time and resources.

also 4:
We should add message to `post-install` script about packages that were built with `-march=native` must be rebuilt(including indirect ones, like musl) without `-march=native` to use them in qemu. Otherwise, you will get errors like: `traps: modprobe[78] trap invalid opcode ip:7ff0dc8c36b2 sp:7fffd351d920 error:0 in libc.so[7ff0dc877000+64000]`

@jedavies-dev
@dilyn-corner

**Comment by jedavies-dev** [comment]
Hi @illiliti
This build worked and ran OK for me starting from a clean KISS chroot and doing "kiss b qemu".

I think the error may be due to other packages you have installed on your system, since the qemu build will enable various features depending on what you have installed. This is not ideal and I think we should explicitly disable more options in the build file to make the build more predictable. If people want extra features they can fork the package locally and enable them.

To help with this, can you please attach the output of "kiss l" and the full build log.

It looks like qemu is in the process of moving to meson but is not there yet.  meson_options.txt does not yet expose all the build options that configure does. Also I have not yet been able to build qemu using the usual meson build style.  Alpine and Void are both still using configure. qemu will build OK without meson being present, but it looks like samurai is required - will add this to the depends.

Regarding the `-march=native` error, is your CPU supported under qemu? If it is then you can use the `-cpu ` option to emulate your model of CPU. This should allow you to run packages built with `-march=native` on qemu.  The following command will show you the supported CPU models: `qemu-system-x86_64 -cpu help`

**Comment by dilyn-corner** [comment]
Directly building with `meson` did not work for me, and I was also able to build `qemu` in a (relatively clean) chroot. I see no good reason not to add that last bit of the Alpine patch. 

I think `qemu` is complicated enough that it warrants specifying a base set of things to include and disabling the rest, if only for the sake of broad system compatibility - like @jedavies-dev said, users who have more 'specific' requirements or intentions should be forking it. 

We should also fix that bashism if we intend to use `sh`.

**Comment by illiliti** [comment]
>  This build worked and ran OK for me starting from a clean KISS chroot and doing "kiss b qemu".

Me too. Rootfs that i used to build qemu: https://github.com/kiss-community/repo-main/releases/download/2021.5-1/kiss-chroot-2021.5-1.tar.xz

> To help with this, can you please attach the output of "kiss l" and the full build log.

Sorry, termbin truncated log for some reason.

Full log: https://envs.sh/Uu.txt
kiss list: https://envs.sh/UF.txt

> but it looks like samurai is required - will add this to the depends.

That would be awesome.

> The following command will show you the supported CPU models: `qemu-system-x86_64 -cpu help`

`-cpu host` did the trick. Thanks for the tip!

**Comment by dilyn-corner** [comment]
Strangely, I yet again cannot build `qemu` in a very fresh chroot, but I CAN build it on my normal system. And i run into the same error @illiliti has.

**Comment by dilyn-corner** [comment]
Closed by 96c0d9b1bbc546a50c4cefa1642898df04533121
