### ISSUE TITLE
Factor v8 out of nodejs and chromium

### ISSUE THREAD

**Issue by noocsharp** [kiss-community/repo-community#77]
The v8 javascript engine takes a long time to compile and is a dependency of both nodejs and chromium. However, it can be built as a shared object, saving the bulk of compilation time for nodejs, and a good chunk for chromium.

It is packaged in the AUR, which can be used as reference:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=v8

**Comment by git-bruh** [comment]
How do you use system v8 for chromium though ? The only mention of it i see is a comment in the [void package](https://github.com/void-linux/void-packages/blob/d00fa5c4e87b72ae59b1818326f667ac4840a976/srcpkgs/chromium/template#L119), nothing in `gn args --list`

As for packaging v8 itself, not sure if we want to package it, seems pretty messy since there's no single tarball and you need to git clone most of the things (without using `depot-tools`) https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/v8.rb + if we need to build `nodejs` with system v8, we'll have to package this mess in the main repo, which dylan probably wouldn't approve of.

**Comment by noocsharp** [comment]
Hmm, when I get some time, I'll play around with it and see if I can figure it out. I thought I'd just throw the idea out there to test the feasibility, and you bring up some good points against it :)

**Comment by noocsharp** [comment]
Closing as I no longer use chromium, and nobody else seems interested in this.
