### ISSUE TITLE
chromium 88.0.4324.150 crash

### ISSUE THREAD

**Issue by kyx0r** [kiss-community/repo-community#85]
@git-bruh Hello git bruh, apparently there is a bug in chromium which causes randonmly pages to hang and crash. 

The kernel reports: 
```
[  383.151955] traps: Chrome_ChildIOT[1063] trap int3 ip:564b399ead3b sp:7f3453bb7170 error:0 in chromium[564b321dd000+ab5a000]
```

When this happens page becomes unresponsive and timeout occurs. Which is obvious why because int3 does stall the cpu until the exception is handled but in this case this is a hard crash of the tab.

I was able to reproduce this with and without hardware acceleration.

The most reliable way to do so is to go to chrome://flags/ and scroll 1 pixel, immediately after that the page hangs and after a little bit it crash.

**Comment by git-bruh** [comment]
Hmm, i have not encountered any such behaviour running with glibc + nvidia and had a successful musl build aswell (though can't test it much)
Void linux doesn't seem to have added any new patches for musl either: https://github.com/void-linux/void-packages/commit/62cfcaa653a5f1dc280efb730052043da06d7e42#diff-4e60bca235f5f2033c89ef4ddfec4821a14b29bf8f88d502f2944ba28721682f

I will boot into my KISS musl subvolume and let you know in sometime.

**Comment by git-bruh** [comment]
Hmm, running from a chroot and opening `chrome://flags` seems to cause the same for me:
```
[  141.992339] traps: Chrome_ChildIOT[2141] trap int3 ip:55d92661dd34 sp:7f55258b02e0 error:0 in chromium[55d921c26000+6684000]
[  212.416457] traps: Chrome_ChildIOT[2514] trap int3 ip:55d92661dd34 sp:7f55258b02e0 error:0 in chromium[55d921c26000+6684000]
```

I think i will try the void linux binary, see if it happens there. If it doesn't, then it might be an issue with one of the system libs we're using like `icu`

**Comment by kyx0r** [comment]
@git-bruh Should I compile firefox? Is it more bloated than chromium ? They added rust, which is the subject of hate. Is there a version without rust? Maybe there is an old version of firefox fork that is maintained by someone before they added the abomination?

**Comment by git-bruh** [comment]
Seems like i broke this since version `87.0.4280.141` which means that it's either caused by:
* system `icu`
* system `libevent`
* system `libxml`
* not linking `libxkbcommon`
* removing `pciutils` dep (`use_libpci=false`)

nothing other than `chrome://flags` seems to be affected. What other pages did you experience this on?

As for firefox, it's definitely less bloated than chromium but I haven't been able to get `85.0.1` to build on KISS, there's `palemoon` if you don't want `rust` but I'd advise against it since it's most likely out of date compared to firefox in terms of security patches and stuff, needs `gtk+2` AND `python2`. Choose your poison :/

**Comment by kyx0r** [comment]
@git-bruh Actually this bug does affect every page. But it happens randomly. I have experienced hangs on youtube.com and zotacstore.com sometimes. i think it just depends on some javascript that runs.

**Comment by dilyn-corner** [comment]
I have also experienced hangs on pages - usually it seems to be red herring (the page works fine on, say, youtube or twitch), but on places like chess.com the entire browser locks up. I will test later with a terminal pulled up to see what it spite out and test the chrome://flags page. FWIW I also think it's javascript related. 
My build can be checked [here](https://github.com/dilyn-corner/KISS-me/blob/master/extra/chromium/build) although I'm not doing anything too special.

**Comment by kyx0r** [comment]
@dilyn-corner Yeah, right? Sometimes when the bug happens it actually does not log any errors, one tab just crashes but after, going forward the whole browser looses ability to load pages, (it's like network died but not really) the pages are just spinning loading forever. When that happens only thing to do is to restart the browser.

**Comment by dilyn-corner** [comment]
Yeah; just tested chrom://flags. The page crashed H A R D. Never experienced just a horrible thing, even on other websites where I get similar issues. No errors in the terminal when it happened either, but I can only assume it's identical to this issue. 

I can test suggested fixes if anybody finds something, but it will take me a full day to rebuild chromium :v

**Comment by git-bruh** [comment]
Rebuilt without `icu` and same issue. On top of that i accidentally rebuilt `88.0.4324.96` instead of `88.0.4324.150` :facepalm: 

Most of the changes I've suggested are already in @dilyn-corner's build file (
*  system `icu` `libxml` `libXslt` are not used
* `use_xkbcommon=true` and pciutils dep is present
*  dilyn's build file has system `libevent` too but that is probably not even remotely related to this issue
)


 no idea how to debug this crap :thinking:

**Comment by git-bruh** [comment]
Did a build without system `libxml`, `libXslt`, `libevent`. Seems to work fine now, I am not interested in further bisecting whether `libevent` is the culprit or (`libxml` + `libXslt`). Will update the build file in sometime.

**Comment by git-bruh** [comment]
Should work with the updated build file now!

**Comment by kyx0r** [comment]
@git-bruh Okay, I have tested the latest build in the last 24hrs and it seems to be stable now. I have not experienced any chrome bugs yet. Looking good! ;)

**Comment by dilyn-corner** [comment]
Coming back to this to confirm (finally) that dropping `libevent` resulted in this being resolved.
